axis gui: fix incremental jog hotkey
This adds a missing global variable that tracks whether a continuous
jog is in progress (and also switches it from int to bool, for clarity).

Before this, attempting to switch from Continuous to Incremental jogging
using `I` or `Shift-I` would produce this error message:

    Exception in Tkinter callback
    Traceback (most recent call last):
      File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1550, in __call__
        return self.func(*args)
      File "/usr/bin/axis", line 3109, in <lambda>
        root_window.bind("i", lambda event: jogspeed_incremental())
      File "/usr/bin/axis", line 1478, in jogspeed_incremental
        if continuous_jog_in_progress: return
    NameError: global name 'continuous_jog_in_progress' is not defined