rtapi_app: explicitly link -ldl
.. because we use symbols from it, such as dlsym()!

It's not clear why this has not always been an error, but it did
become one when using gcc -fsanitize-address to build LinuxCNC:

    /usr/bin/ld: objects/rtapi/uspace_rtapi_app.o:
        undefined reference to symbol 'dlsym@@GLIBC_2.2.5'