Introducing destructor to os_intf/inetnull.cc
Looked into this because of this error message, which is a false
positive that should be reported to cppcheck:

os_intf/inetnull.cc:45:5: error: Resource leak: fp [resourceLeak]
    return inet_file;