pluto: use rtapi's fabs() instead of the kernel's abs()
This fixes a build problem on Linux 4.4-rtai:

/usr/src/linux-headers-4.4.0-0.bpo.2-common-rtai/scripts/Makefile.build:263: recipe for target '/home/seb/linuxcnc-dev/src/objects/hal/drivers/pluto_step.o' failed
/usr/src/linux-headers-4.4.0-0.bpo.2-common-rtai/Makefile:1417: recipe for target '_module_/home/seb/linuxcnc-dev/src' failed
Makefile:150: recipe for target 'sub-make' failed
Makefile:8: recipe for target 'all' failed
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-0.bpo.2-rtai-686-pae'
Makefile:10: *** mixed implicit and normal rules: deprecated syntax
In file included from /usr/src/linux-headers-4.4.0-0.bpo.2-common-rtai/include/linux/list.h:8:0,
                 from /usr/src/linux-headers-4.4.0-0.bpo.2-common-rtai/include/linux/module.h:9,
                 from /home/seb/linuxcnc-dev/src/rtapi/rtapi.h:782,
                 from /home/seb/linuxcnc-dev/src/objects/hal/drivers/pluto_step.c:2:
hal/drivers/pluto_step.comp: In function ‘write’:
/usr/src/linux-headers-4.4.0-0.bpo.2-common-rtai/include/linux/kernel.h:225:43: error: void value not ignored as it ought to be
 #define __abs_choose_expr(x, type, other) __builtin_choose_expr( \
                                           ^
/usr/src/linux-headers-4.4.0-0.bpo.2-common-rtai/include/linux/kernel.h:215:16: note: in expansion of macro ‘__abs_choose_expr’
 #define abs(x) __abs_choose_expr(x, long long,    \
                ^
hal/drivers/pluto_step.comp:217:21: note: in expansion of macro ‘abs’
make[4]: *** [/home/seb/linuxcnc-dev/src/objects/hal/drivers/pluto_step.o] Error 1

Signed-off-by: Sebastian Kuzminsky <seb@highlab.com>