Fix tests/startup-state
Fixes:
 File "./test-ui.py", line 22
    print "acceleration:", status.acceleration
                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("acceleration:", status.acceleration)?

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>