Fix tests/trajectory-planner
Fixes:
  File "./trajectory-planner/circular-arcs/run_all_tests.py", line 51
    print "In folder {0}, found {1} files:".format(testpath,len(files))
                                          ^
SyntaxError: invalid syntax

 File "./trajectory-planner/circular-arcs/run_all_tests.py", line 51
    print "In folder {0}, found {1} files:".format(testpath,len(files))
                                          ^
SyntaxError: invalid syntax

  File "./trajectory-planner/circular-arcs/machine_setup.py", line 39
    print "No G code specified, setup complete"
                                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("No G code specified, setup complete")?

  File "./trajectory-planner/circular-arcs/linuxcnc_control.py", line 125
    print "interrupted by keyboard in c.wait_complete(self.timeout)"
                                                                   ^
SyntaxError: invalid syntax

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>