Fix TypeError: a bytes-like objectis required, not'str’ (fixes #840)
Fixes the following exceptions:

For python3:
Traceback (most recent call last):
  File "/home/sw/projects/machinekit/linuxcnc/lib/python/stepconf/pages.py", line 91, in on_button_fwd_clicked
    self['%s_finish'%name]()
  File " fhome/sw/projects/machinekit/linuxcnc/lib/python/stepconf/pages.py", line 881, in finished_finish
    self.a.buid_config()
  File "/home/sw/projects/machinekit/linuxcnc/bin/stepconf”, line 795, in buid_config
    self.d.save(base)
  File "/home/sw/projects/machinekit/linuxcnc/bin/stepcont", line 680, in save
    d.writexml(open((filename, "wb"), addindent=" ", newl="\n")
  File "/usr/lib/python3.7/xml/dom/minidom.py", line 1791, in writexml
    writer.write('<?xml version="1.0" ?>'+newl)
  TypeError: a bytes-like objectis required, not'str’

Above generates empty ~/.stepconf-preferences which in turns triggers the next exception
(applicable for both python2/3):

Traceback (most recent call last):
  File "/home/sw/projects/machinekit/linuxcnc/bin/stepconf", line 1576, in <module>
    app = StepconfApp(False)
  File "/home/sw/projects/machinekit/linuxcnc/bin/stepconf", line 770, in __init__
    self.d.load_preferences()
  File "/home/sw/projects/machinekit/linuxcnc/bin/stepconf", line 515, in load_preferences
    d = xml.dom.minidom.parse(open(filename, "r"))
  File "/usr/lib64/python2.7/xml/dom/minidom.py", line 1918, in parse
    return expatbuilder.parse(file)
  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 928, in parse
    result = builder.parseFile(file)
  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 211, in parseFile
    parser.Parse("", True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0

For the last one the warning-dialog is now diplayed depicting the problem to the user.

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>