interp: it's nonsense to take a boost::cref(this)
The intent was to take a reference to the Interp object being
constructed, which is "*this".

This also fixes a compilation error reported with boost 1.58:
emc/rs274ngc/rs274ngc_pre.cc:133:57: error: use of deleted function
    'void boost::cref(const T&&) [with T = Interp*]'
  _setup.pythis =  boost::python::object(boost::cref(this));

/usr/include/boost/core/ref.hpp:179:24: error: declared here
template<class T> void cref(T const&&) BOOST_REF_DELETE;

Signed-off-by: Bernhard M. Wiedemann <bwiedemann@suse.de>