Fix tests/statbuffer-g5x-abort
Fixes:
  File "./test-ui.py", line 53
    print "Current coordinate system is G%d, not G55" % \
                                                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Current coordinate system is G%d, not G55" % \)?

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>