Fix tests/halui/mdi
Fixes the following errors:
 File "test-ui.py", line 19
    print "%.3f: %s" % (delta_t, msg)
                   ^
SyntaxError: invalid syntax
  File "test-ui.py", line 19
    print()"%.3f: %s" % (delta_t, msg))
                    ^
SyntaxError: invalid syntax
  File "test-ui.py", line 70
    print "halui reports mode", pin_name
                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("halui reports mode", pin_name)?

  File "test-ui.py", line 73
    print "timeout waiting for halui to report mode", pin_name
                                                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("timeout waiting for halui to report mode", pin_name)?

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>