Stop uploading debs and PDFs are CI artifacts, as it tend to fail
The error from the CI run often look like this:

  Error: Unexpected response. Unable to upload chunk to
  https://pipelines.actions.githubusercontent.com/6HFjJw6TOQMbFXejq4N2A23YIPH3V5KpoRi1gRrwgzu6uIGnXP/_apis/resources/Containers/21487281?itemPath=PDFs%2FLinuxCNC_Documentation.pdf

I believe the cause is that the artifacts are too big to reliably be uploaded to the
github artifact repository.

This reverts 24921d174c4d5e28bedb77f12437031a404f0287.