axis: Workaround active axis selection issues on amd64
On amd64 the active axis selection 'current_axis' sometimes is set to an incorrect value, possibly by tk(inter).
Work around this by force-setting the variable in the radio button callback.

Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1545, in __call__
    return self.func(*args)
  File "/home/mb/develop/git/machinekit/bin/axis", line 2465, in touch_off
    offset_axis = "xyzabcuvw".index(vars.current_axis.get())
ValueError: substring not found