build: fix dependency analyis after changing branches
this fixes incomplete dependency analysis after switching from
v2.5_branch to master branch, the overt symptom of which was a failing
build with an error like this:
emcIniFile.cc:66: undefined reference to
 `IniFile::Find(int*, IniFile::StrIntPair*, char const*, char const*, int)'

fix this by reading the dependency information from where v2.5_branch
would have left it if there's not one where we would have created it.