eoffset_per_angle avoid name clash (debian buster)
------------------------------------------------------------
make on debian buster:
...
$ halcompile --compile hal/components/eoffset_per_angle.c
Compiling realtime eoffset_per_angle.c
...
eoffset_per_angle.c:240:15: error: expected identifier or ‘(’ before numeric constant
 #define fmul (0+*__comp_inst->fmul)
------------------------------------------------------------
$ gcc --version
gcc (Debian 8.2.0-12) 8.2.0
$ lsb_release -crd
Description:	Debian GNU/Linux buster/sid
Release:	testing
Codename:	buster
------------------------------------------------------------
problem occurs for name clashes like fmul, fmull, dmull, etc.
------------------------------------------------------------

Note: the buster package: yapps2 provides /usr/bin/yapps2
      but it does not work with halcompile -- likely due
      to python3 implementation changes

      build of LinuxCNC was tested using a /usr/local/bin/yapps
      copied from 2.7 branch (fc6eb7f20 deletes it)