Fix Cython build because of enum type
The code generated by Cython failed to build with newer versions of gcc, caused
by function passing wrong enum type:

  Compiling hal/cython/machinekit/hal.c
  hal/cython/machinekit/hal.c:1177:59: error: unknown type name ‘comp_type’
  static CYTHON_INLINE PyObject* __Pyx_PyInt_From_comp_type(comp_type value);

To fix the issue, this patch creates typedef for all enums in HAL, and refer to
the proper type in hal_const.pxd. It just normalize the code, because other
enums were already using a typedef, except comp_type, compt_state and
report_phase.

Signed-off-by: Francis Giraldeau <francis.giraldeau@gmail.com>