xhc-hb03: link with -lstdc++
at least wheezy requires this:
Linking xhc-hb04
/usr/bin/ld: objects/hal/user_comps/xhc-hb04.o: undefined reference to symbol '__gxx_personality_v0@@CXXABI_1.3'
//usr/lib/i386-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [../bin/xhc-hb04] Error 1