xemc: explicitly link with libXt
Possibly when I changed from the bfd linker to the gold linker,
my 32-bit Ubuntu 10.04 started encountering link errors when building
xemc.  One example out of many:
 emc/usr_intf/xemc.cc:1279: error: undefined reference to 'XtVaSetValues'

xemc does explicitly and directly use functions from libXt, so it's
right to name it on the link line.