fix crash loading empty file
Using infinity instead of the old 9e99 led to tracebacks like
    File "/home/git/emc2-dev/lib/python/glnav.py", line 366, in set_view_p
      size = (size[0] ** 2 + size[1] ** 2 + size[2] ** 2) ** .5
  OverflowError: (34, 'Numerical result out of range')
most trivially seen with a file containing the single line "M2".