Fix tests/motion-logger/basic
Fixes:
  File "./test-ui.py", line 32
    print "sub-test %s ok" % logfile_name
                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("sub-test %s ok" % logfile_name)?

  File "./test-ui.py", line 81
    print("trying to exit", file=sys.stderr)
                                ^
SyntaxError: invalid syntax

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>