Fix tests/lathe
Fixes:
  File "./test-ui.py", line 55
    print "running gcode:", gcode
                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("running gcode:", gcode)?

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>