Fix tests/ccomp/early-exit
Fixes the following error:
  File "test-ui.py", line 70
    print "position:", s.position
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("position:", s.position)?

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>