Fix tests/remap
Fixes:
  File "./remap/sequencing/permute.py", line 41
    print perm
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(perm)?

  File "./remap/introspect/oword.py", line 37
    print "debug: ", self.debugmask,"logging:",self.loggingLevel
                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("debug: ", self.debugmask,"logging:",self.loggingLevel)?

 File "./remap/oword-pycall/oword.py", line 37
    print "multiply: number of arguments=", len(args)
                                         ^
SyntaxError: invalid syntax

 File "./oremap/introspec/tword.py", line 41
    print("args=(", end=' ')
                       ^
SyntaxError: invalid syntax

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>