Fix tests/tool-info/random-with-startup-tool
Fixes:
  File "./test-ui.py", line 57
    print "nothing from polling error channel"
                                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("nothing from polling error channel")?

Sorry: TabError: inconsistent use of tabs and spaces in indentation (test-ui.py, line 64)

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>