Fix tests/halmodule.0
Fixes various python errors e.g.:
  File "<stdin>", line 14
    print "set", p, v, h[p]
              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("set", p, v, h[p])?

Fixes python code to be python2 and python3 compatible.
Extract the code to a separate file to be able to check the python
syntax easily. Verified with both:
 $ python2 -m py_compile test.py
 $ python3 -m py_compile test.py

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>